/// DAWEN Bonding Curve Program
///
/// A pump.fun-style virtual-reserve bonding curve that lets any SPL token
/// trade immediately at launch without the creator depositing real SOL
/// liquidity. The curve price emerges from a constant-product invariant
/// (k = virtual_sol * virtual_token) using configurable initial reserves.
///
/// Instructions
/// ────────────
/// 1. initialize_launch  — wire up curve parameters, move token allocation
///                          into the program-owned token vault
/// 2. buy                — user sends SOL, receives tokens, price rises
/// 3. sell               — user sends tokens, receives SOL, price falls
/// 4. graduate           — permissionless graduation once threshold is met
///
/// Vaults
/// ──────
/// • SOL vault  — PDA (seeds: ["sol_vault", mint])   holds real SOL
/// • Token vault — ATA of LaunchState PDA             holds unsold tokens
///
/// Both vaults are program-owned. The frontend/creator cannot withdraw
/// directly.
///
/// Treasury
/// ────────
/// Platform fees go to: FvzoyNk8MSwMgWbiGRbhLASyJSusoVpVtaE2w11WFg2X
///
/// Program ID placeholder
/// ──────────────────────
/// Replace DCurve1vZEq4cPjhfRDsGBrXJGBnwuQ8LqFp5gNmpBJv with the key
/// generated by `anchor keys list` before deploying.
use anchor_lang::prelude::*;

pub mod errors;
pub mod instructions;
pub mod math;
pub mod state;

use instructions::*;

declare_id!("DCurve1vZEq4cPjhfRDsGBrXJGBnwuQ8LqFp5gNmpBJv");

/// DAWEN platform fee treasury address.
/// All buy/sell platform fees are forwarded here atomically in the same
/// transaction as the trade.
pub const TREASURY: Pubkey = pubkey!("FvzoyNk8MSwMgWbiGRbhLASyJSusoVpVtaE2w11WFg2X");

/// Seed for LaunchState PDA: [LAUNCH_SEED, mint.key()].
pub const LAUNCH_SEED: &[u8] = b"launch";

/// Seed for SOL vault PDA: [SOL_VAULT_SEED, mint.key()].
pub const SOL_VAULT_SEED: &[u8] = b"sol_vault";

#[program]
pub mod dawen_curve {
    use super::*;

    /// Create a new bonding curve launch for an existing SPL token mint.
    ///
    /// Transfers `curve_token_allocation` tokens from the creator's ATA into
    /// the program-owned token vault. Sets virtual reserves, graduation
    /// threshold, and platform fee. Status starts as Active.
    pub fn initialize_launch(
        ctx: Context<InitializeLaunch>,
        args: InitializeLaunchArgs,
    ) -> Result<()> {
        instructions::initialize_launch::handler(ctx, args)
    }

    /// Buy tokens through the bonding curve with SOL.
    ///
    /// Platform fee is deducted from sol_amount first; the remainder enters
    /// the constant-product formula to derive tokens_out. Fails if:
    ///   - launch is not Active
    ///   - tokens_out < min_tokens_out (slippage)
    ///   - token vault has insufficient tokens
    ///
    /// Auto-graduates the launch if realSolCollected reaches the threshold.
    pub fn buy(ctx: Context<Buy>, args: BuyArgs) -> Result<()> {
        instructions::buy::handler(ctx, args)
    }

    /// Sell tokens back to the bonding curve for SOL.
    ///
    /// The curve returns gross SOL; platform fee is deducted; net SOL goes to
    /// the seller. Fails if:
    ///   - launch is not Active
    ///   - net_sol_out < min_sol_out (slippage)
    ///   - SOL vault has insufficient lamports
    pub fn sell(ctx: Context<Sell>, args: SellArgs) -> Result<()> {
        instructions::sell::handler(ctx, args)
    }

    /// Explicitly graduate the launch once realSolCollected >= threshold.
    ///
    /// Permissionless — anyone can call this. The `buy` instruction also
    /// auto-graduates, so this is a fallback for edge cases.
    /// After graduation, buy/sell are permanently blocked and vault funds are
    /// preserved for a future Raydium/Meteora migration instruction.
    pub fn graduate(ctx: Context<Graduate>) -> Result<()> {
        instructions::graduate::handler(ctx)
    }
}
